on:
  workflow_dispatch:
  release:
    types: [published, created]

jobs:
  copy_update_branch:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Clone external repository
        run: |
          git clone --branch update --depth 1 ${{ secrets.REPO }} external-repo
        working-directory: ${{ github.workspace }}

      - name: Push update branch
        run: |
          cp -r external-repo/* .
          rm -rf external-repo
        working-directory: ${{ github.workspace }}


      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: update
          skip_checkout: true
          file_pattern: build.md *-update.json
          commit_message: Bump version
        
