on:
  workflow_dispatch:
  release:
    types: [published, created]

jobs:
  copy_update_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Clone external repository
        run: |
          git clone --branch update --depth 1 ${{secrets.REPO}} external-repo
        working-directory: ${{ github.workspace }}

      - name: Push update branch
        run: |
          cd external-repo
          git remote set-url origin https://github.com/${{ github.repository }}.git
        working-directory: ${{ github.workspace }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 'update'