on:
  workflow_dispatch:
  release:
    types: [published, created]

jobs:
  copy_update_branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Clone external repository
        run: |
          git clone --branch update --depth 1 ${{secrets.REPO}} external-repo
        working-directory: ${{ github.workspace }}

      - name: Push update branch
        run: |
          cd external-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git remote set-url origin ${{ github.repository }}
          git push origin update:refs/heads/update
        working-directory: ${{ github.workspace }}